config/routes.rb
  Rails.application.routes.draw do
  get 'likes/create'
  get 'likes/destroy'
  get 'reviews/index'
  get "start", to: "static_pages#start"
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks",
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  get "alltags", to: "static_pages#alltags"
  get "search", to: "reviews#search"
  root 'static_pages#home'

  resources :schools do
    collection do   
      get :search
    end
    resources :reviews do
      resources :comments
    end
  end
  resources :likes, only: [:destroy, :create]  
  resources :notifications, only: :index
  resources :categories, only: [:index, :show, :new, :create, :destroy]
  resources :profiles, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :review_category_relations
  has_many :reviews, through: :review_category_relations
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review
  has_many :notifications, dependent: :destroy
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :review
  counter_culture :review
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :review, optional: true
  belongs_to :comment, optional: true
  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar
end

app/models/review.rb
class Review < ApplicationRecord
  acts_as_taggable
  belongs_to :user
  belongs_to :school
  has_many :review_images, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_rev_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  accepts_attachments_for :review_images, attachment: :image
  has_many :notifications, dependent: :destroy
  has_many :review_category_relations
  has_many :categories, through: :review_category_relations
  validates :title, presence: true, length: { maximum: 50 }
  validates :body, presence: true

  def like_rev(user)
    likes.create(user_id: user.id)
  end

  def un_like_rev(user)
    likes.find_by(user_id: user.id).destroy
  end

  def like_rev?(user)
    like_rev_users.include?(user)
  end

  def self.search(search)
    if search
      Review.where(['body LIKE ? OR title LIKE ?', "%#{search}%", "%#{search}%"])
    else
      Review.all
    end
  end

  def create_notification_like!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and review_id = ? and action = ? ", current_user.id, user_id, id, 'like'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        review_id: id,
        visited_id: user_id,
        action: 'like'
      )
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_user, comment_id)
    temp_ids = Comment.select(:user_id).where(review_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    notification = current_user.active_notifications.new(
      review_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/models/review_image.rb
class ReviewImage < ApplicationRecord
  belongs_to :review
  attachment :image
end

app/models/school.rb
class School < ApplicationRecord
  has_many :reviews, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  validates :address, presence: :true
  validates :res_id, uniqueness: true
  validates :name, presence: true
  scope :sorted, -> { order(created_at: :desc) }

  scope :search, -> (search_params) do
    return if search_params.blank?
    name_like(search_params[:name]).nation_is(search_params[:nation]).genre_is(search_params[:genre])
  end


  scope :name_like, -> (name) { where('name LIKE ?', "%#{name}%") if name.present? }
  scope :nation_is, -> (nation) { where('nation LIKE ?', "%#{nation}%") if nation.present? }
  scope :genre_is, -> (genre) { where('genre LiKE ? OR subgenre LIKE ?', "%#{genre}%", "%#{genre}%") if genre.present? }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :omniauthable, omniauth_providers: [:twitter]
  before_create :create_profile

  has_one :profile, dependent: :destroy
  has_many :review, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  def self.from_omniauth(auth)
    find_or_create_by(provider: auth["provider"], uid: auth["uid"]) do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.username = auth["info"]["nickname"]
      user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"]) do |user|
        user.attributes = params
      end
    else
      super
    end
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.username = "ゲストユーザー"
      user.confirmed_at = Time.now 
    end
  end

  private

  def create_profile
    build_profile
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.new(comment_params)
    @comment.user_id = current_user.id
    @review = @comment.review
    if @comment.save
      @review.create_notification_comment!(current_user, @comment.id)
      render :index
    else
      render :error
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      render :index
    else
      redirect_back(fallback_location: school_review_path(id: @review.id))
    end
  end

  private

  def comment_params
    params.permit(:body, :review_id)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
      title:       "School Review",
      description: "フィリピン／オーストラリアの語学学校レビューアプリ",
      keywords:    "フィリピン,オーストラリア,語学学校, 留学エージェント, Ruby, Rails",
      icon: image_url("/images/favicon.ico"), # favicon
      noindex: ! Rails.env.production?, # production環境以外はnoindex  
      charset: "UTF-8",
      # OGPの設定
      og: {
        title: "School Review",
        type: "website",
        url: request.original_url,
        image: image_url("/images/slide8.png"),
        site_name: "School Review",
        description: "フィリピン／オーストラリアの語学学校レビューアプリ",
        locale: "ja_JP"
      } 
    }
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/health_check_helper.rb
module HealthCheckHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/comments/_error..html.erb
<% if comment.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <%= render partial: 'form', locals: { comment: @comment, review: @review } %>
<% end %>

app/views/comments/_error.html.erb
<% if comment.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <%= render partial: 'form', locals: { comment: @comment, review: @review } %>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(url: school_review_comments_path(review_id: review.id) ) do |form| %>
  <div id="comment_area">
    <%= form.text_area :body, class:"form-control mt-5", style: "width: 22em;" %>
    <%= form.hidden_field :review_id, value: review.id %><br>
  </div>
  <div class="actions">
    <%= button_tag type: "submit", class: "btn-comment", id: "btn-comment" do %>
      <i class="fa fa-commenting" aria-hidden="true"></i>
      コメントする
    <% end %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<div id="comments_area">
  <h1 class="comments_title">コメント</h1>
  <% if comments.present? %>
    <% comments.each do |comment| %>
      <% if comment.user == current_user %>
        <div class="comment-area">
          <div class="my-box24">
            <p><%= safe_join(comment.body.split("\n"), tag(:br)) %></p>
          </div>
          <div class="my-comment-user">
            <%= link_to school_review_comment_path(review_id: comment.review_id, id: comment.id), method: :delete, remote: true, data: {confirm: "このコメントを削除しますか？" } do %>
              <i class="fa fa-trash-o comment-destroy" aria-hidden="true" id="comment-destroy"></i>
            <% end %>
            <div class="my-comment-user-name">
              <%= link_to profile_path(id: comment.user.profile.id) do %>
                <%= render 'layouts/profile_icon', profile: comment.user.profile %>
                <%= comment.user.profile.name %>さん
              <% end %>
            </div>
          </div>
        </div>
      <% else %>
        <div class="comment-area">
          <div class="box24">
            <p><%= safe_join(comment.body.split("\n"), tag(:br)) %></p>
          </div>
          <div class="comment-user">
            <%= link_to profile_path(id: comment.user.profile.id) do %>
              <%= render 'layouts/profile_icon', profile: comment.user.profile %>
              <%= comment.user.profile.name %>さん
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <div class="comment-area">
      <p class="nil-comment">まだコメントはありません</p>
    </div>
  <% end %>
</div>

app/views/comments/error.js.erb
$("#comments_area").html("<%= j(render 'index', { comments: @comment.review.comments }) %>");
$("#error_area").html("<%= j(render 'error', { comment: @comment }) %>");

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'index', { comments: @comment.review.comments }) %>");
$('#error_explanation').remove();
$("textarea").val('');