config/routes.rb
  Rails.application.routes.draw do
  get 'likes/create'
  get 'likes/destroy'
  get 'reviews/index'
  get "start", to: "static_pages#start"
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks",
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  get "alltags", to: "static_pages#alltags"
  get "search", to: "reviews#search"
  root 'static_pages#home'

  resources :schools do
    collection do   
      get :search
    end
    resources :reviews do
      resources :comments
    end
  end
  resources :likes, only: [:destroy, :create]  
  resources :notifications, only: :index
  resources :categories, only: [:index, :show, :new, :create, :destroy]
  resources :profiles, only: [:show, :edit, :update]
end

app/models/school.rb
class School < ApplicationRecord
  has_many :reviews, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  validates :address, presence: :true
  validates :res_id, uniqueness: true
  validates :name, presence: true
  scope :sorted, -> { order(created_at: :desc) }

  scope :search, -> (search_params) do
    return if search_params.blank?
    name_like(search_params[:name]).nation_is(search_params[:nation]).genre_is(search_params[:genre])
  end


  scope :name_like, -> (name) { where('name LIKE ?', "%#{name}%") if name.present? }
  scope :nation_is, -> (nation) { where('nation LIKE ?', "%#{nation}%") if nation.present? }
  scope :genre_is, -> (genre) { where('genre LiKE ? OR subgenre LIKE ?', "%#{genre}%", "%#{genre}%") if genre.present? }
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  include AjaxHelper
#  before_action :sign_in_required, only: [:new]

  def index
    @search_params = school_search_params
    @schools = School.search(@search_params).order(created_at: "DESC").page(params[:page]).per(9)
    all_genre = School.pluck(:subgenre)
    @genres = all_genre.uniq.reject(&:blank?)
    all_nation = School.pluck(:nation)
    @nations = all_nation.uniq.reject(&:blank?)
  end

  def show
    @school = School.find(params[:id])
    @reviews = @school.reviews.order(created_at: "DESC").page(params[:page]).per(4)
  end
  
  def new
    @school = School.new
  end

  def search
    @school = School.where('name like ?', "%#{params[:name]}%")
    @user = User.last
    respond_to do |format|
      format.html
      format.json{render json:{school:@school}}
    end
  end

  def create
    @school = School.new(      
      name: params[:name],
      address: params[:address],
      tell: params[:tell],
      latitude: params[:latitude],
      longitude: params[:longitude],
      image_url_a: params[:image_url_a],
      image_url_b: params[:image_url_b],
      detail: params[:detail],
      genre: params[:genre],
      subgenre: params[:subgenre],
      opentime: params[:opentime],
      res_id: params[:res_id],
      nation: params[:nation]
    )
    if @school.save
      puts "保存しました"
      respond_to do |format|
        format.js do
          render ajax_redirect_to(new_school_review_path(school_id: @school.id))
        end
      end
    else
      puts "すでに保存されてます"
      @sch = School.find_by(res_id: @school.res_id)
      respond_to do |format|
        format.js do
          render ajax_redirect_to(new_school_review_path(school_id: @sch.id))
        end
      end
    end
  end

  private

  def school_search_params
    params.fetch(:search, {}).permit(:name, :nation, :genre)
  end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_genre.html.erb
<% if school.genre == school.subgenre %>
  <span class="badge badge-pill badge-info mr-1 mt-1 p-2">
    <%= school.genre %>
  </span>
<% elsif school.subgenre.blank? %>
  <span class="badge badge-pill badge-info mr-1 mt-1 p-2">
    <%= school.genre %>
  </span>
<% else %>
  <span class="badge badge-pill badge-info mr-1 mt-1 p-2">
    <%= school.genre %>
  </span>
  <span class="badge badge-pill badge-success mr-1 mt-1 p-2">
    <%= school.subgenre %>
  </span>
<% end %>

app/views/schools/_school_details.html.erb
<div class="row">
  <div class="rev-card-school-details col-12">
    <!-- 学校名 -->
    <div class="col">
      <div class="title-school">
        <%= link_to school.name, school_path(id: school.id) %>
      </div>  
    </div>
    <!-- 学校の説明 -->
    <div class="col-lg-6 float-left">
      <h4><%= school.tell %></h4>
      <br>
      <h6><i class="fa fa-comment" aria-hidden="true"></i> <%= school.detail %></h6>
      <p style="color: gray"><i class="fa fa-home" aria-hidden="true" ></i> <%= school.address %></p>
      <p style="color: gray"><i class="fa fa-circle-o" aria-hidden="true"></i> <%= school.opentime %></p>
      <p><%= render "schools/genre", school: school %></p>
    </div>
    <!-- 学校写真 -->
    <div class="col-lg-5 float-right">
      <%= render "schools/school_photo_slide", school: school %>
    </div>
    <div id="map"></div>   
  </div>
</div>

<script type="text/javascript">
  function initMap() {
// latitude,longitudeから位置を特定
    var test ={lat: <%= school.latitude %>, lng: <%= school.longitude %>};
    var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 15, 
              center: test
              });
    var transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);

    var contentString = '住所：<%= school.address %>';
    var infowindow = new google.maps.InfoWindow({
      content: contentString
    });

 // Map上の指定した位置にピンを挿して表示する
    var marker = new google.maps.Marker({
                  position:test,
                  map: map,
                  title: contentString
                 });

     marker.addListener('click', function() {
       infowindow.open(map, marker);
     });
  }
</script>

<script async defer
              src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLEMAP_API_KEY'] %>&callback=initMap">
</script>

app/views/schools/_school_photo_slide.html.erb
<div class="slide">
  <img src="<%= school.image_url_a %>" alt="">
  <img src="<%= school.image_url_b %>" alt="">
</div>

app/views/schools/_search_form.html.erb
<nav class="search-box justify-content-right" style="background-color:#C2EEFF;">
  <div class="nav-wrapper row">

<div class="container">  
      <div class="row">
        <!-- 学校名検索バー -->
        <div class="search-bar1 col-md-4">
          <%= form_with(scope: :search, url: schools_path, method: :get, local: true) do |f| %>
          <%= f.text_field :name, value: @search_params[:name], placeholder: "学校の名前を検索" %>
        </div>

        <!-- 国検索バー -->
        <div class="search-bar2 search-option col-md-4">
          <%= f.select(:nation, @nations, include_blank: "学校のある国を選択") %>
        </div>

        <!-- ジャンル選択バー -->
        <div class="search-bar2 search-option col-md-4">
          <%= f.select(:genre, @genres, include_blank: "エリアを選択") %>
        </div>
        
        <!-- 検索ボタン -->
        <div class="btn-search-area float-right">
          <%= button_tag type: "submit", class: "btn btn-outline-info" do %>
            <i class="fa fa-search" aria-hidden="true"></i>
            検索
          <% end %>
        </div>
      </div>
      <% end %>
      </div>
    </div>
</nav>

app/views/schools/_slide.html.erb
<div class="container-fluid">
	<div class="row">
             <div class="col-xs-12 top2">
                  <div class="cover-text text-center">
				<p style="color: #fff;">語学学校リスト</p>
			</div>
		</div>
	</div>
</div>

app/views/schools/index.html.erb
<% provide(:title, "語学学校リスト")  %>  
<%= render "slide" %>
<%= render "search_form" %>

<div class="container">  
  <div class="row">
    <% @schools.each do |school| %>
    <div class=" col-lg-4">
    <%= link_to school_path(id: school.id) do %>
      <div class="card mt-5 shadow-sm" style="width: 20rem; margin: auto;">
        <% if school.image_url_a.present? %>
          <%= image_tag "#{school.image_url_a}", class: "card-img-top"%>
        <% else %>
          <%= image_tag "#{school.image_url_b}", class: "card-img-top"%>
        <% end %>
        <div class="card-body webkit-center">
          <div class="title-school-index"><%= school.name %></div>
          <p class="card-text"><%= render "genre", school: school %></p>
          <p class="school-card-text">
            <i class="fa fa-comment" aria-hidden="true"></i>
            レビュー件数 <%= school.reviews.count %> 件</p>
        </div>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>
  <div class='kaminari_paginate'>
    <%= paginate @schools %>
  </div>

app/views/schools/new.html.erb
<% provide(:title, "学校検索")  %>
<div class="container">
  <%= link_to root_path, class:"btn-back" do %>
    <i class="fa fa-arrow-left" aria-hidden="true"></i> Back
  <% end %>
  <div class="footerpt">
  <div class="row">
    <div class="col-12">
      <div class="rev-card px-2 pb-2 pt-2">
        <h1 class="title-h1">レビューする学校を検索してください</h1>
        <div class="result"></div>
        <div class="webkit-center mt-5">
          <input type="text" name="namae" id="name" class="form-control mr-sm-2 x-300 mt-4" placeholder="学校名を入力">
          <%= button_tag type: "submit", class: "btn btn-info inline mt-2 mb-4", id: "school_search" do %>
          <i class="fa fa-search" aria-hidden="true"></i>
          検索
          <% end %>
        </div>
        <div class="row" id="school_lists"></div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/schools/show.html.erb
<% provide(:title, @school.name) %>
  <div class="container">
    <%= link_to :back, class:"btn-back" do %>
      <i class="fa fa-arrow-left" aria-hidden="true"></i> Back
    <% end %> 

    <div class="row">
      <div class="col">
        <!-- 学校の詳細ページ -->
        <%= render "school_details", school: @school %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-2 col-md-offset-5">
        <%= link_to new_school_review_path(school_id: @school.id), class:"btn-new-review-show" do %>
          <i class="fa fa-check" aria-hidden="true"></i>学校のレビュー投稿
        <% end %> 
      </div>
    </div>

    <!-- レビューリスト -->
    <div class="row"> 
      <div class="col">
        <div class="footerpt">
        <h1 class="title-rev"><%= @school.name %>のレビューリスト</h1>
        <%= render "layouts/review_index", reviews: @reviews %>
      </div>
      </div>
    </div>
    <%= paginate @reviews %>
  </div>