config/routes.rb
  Rails.application.routes.draw do
  get 'likes/create'
  get 'likes/destroy'
  get 'reviews/index'
  get "start", to: "static_pages#start"
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks",
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  get "alltags", to: "static_pages#alltags"
  get "search", to: "reviews#search"
  root 'static_pages#home'

  resources :schools do
    collection do   
      get :search
    end
    resources :reviews do
      resources :comments
    end
  end
  resources :likes, only: [:destroy, :create]  
  resources :notifications, only: :index
  resources :categories, only: [:index, :show, :new, :create, :destroy]
  resources :profiles, only: [:show, :edit, :update]
end

app/models/review.rb
class Review < ApplicationRecord
  acts_as_taggable
  belongs_to :user
  belongs_to :school
  has_many :review_images, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_rev_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  accepts_attachments_for :review_images, attachment: :image
  has_many :notifications, dependent: :destroy
  has_many :review_category_relations
  has_many :categories, through: :review_category_relations
  validates :title, presence: true, length: { maximum: 50 }
  validates :body, presence: true

  def like_rev(user)
    likes.create(user_id: user.id)
  end

  def un_like_rev(user)
    likes.find_by(user_id: user.id).destroy
  end

  def like_rev?(user)
    like_rev_users.include?(user)
  end

  def self.search(search)
    if search
      Review.where(['body LIKE ? OR title LIKE ?', "%#{search}%", "%#{search}%"])
    else
      Review.all
    end
  end

  def create_notification_like!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and review_id = ? and action = ? ", current_user.id, user_id, id, 'like'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        review_id: id,
        visited_id: user_id,
        action: 'like'
      )
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_user, comment_id)
    temp_ids = Comment.select(:user_id).where(review_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    notification = current_user.active_notifications.new(
      review_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_review, only: [:show, :edit, :update, :destroy]
  before_action :find_school, only: [:show, :new, :edit, :create, :update]
  before_action :sign_in_required, only: [:new, :edit]
  before_action :validate_user, only:[:edit, :update, :destroy]

  def index
    @reviews = Review.all.order(created_at: "DESC").page(params[:page]).per(8)
  end

  def show
    @comment = Comment.new 
    @comments = @review.comments.page(params[:page]).per(5)
  end

  def new
    @review = Review.new
    @review.review_images.build
  end

  def edit
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.school_id = @school.id
    if @review.save
      flash[:notice] = "レビューを作成できました"
      redirect_to school_review_path(id: @review.id)
    else
      flash.now[:alert] = "レビューの作成に失敗しました。詳細はタイトル入力欄上のエラーメッセージをご確認ください。"
      render :new
    end
  end

  def update
    if @review.update(review_params)
      redirect_to school_review_path(id: @review.id), notice: "更新しました"
    else
      flash.now[:alert] = "更新に失敗しました。詳細はタイトル入力欄上のエラーメッセージをご確認ください。"
      render :edit
    end
  end

  def destroy
    if @review.destroy
      redirect_to root_path, notice: "削除しました"
    else
      flash[:alert] = "削除に失敗しました。"
      redirect_to school_review_path(id: @review.id)
    end
  end

  def search
    if params[:search].blank?
      redirect_back fallback_location: root_path, notice: "検索キーワードを入力してください"
    else
      @reviews = Review.search(params[:search]).order(created_at: "DESC").page(params[:page]).per(3)
    end
  end
  
  private

  def find_review
    @review = Review.find(params[:id])
  end

  def find_school
    @school = School.find(params[:school_id])
  end

  def review_params
    params.require(:review).permit(:title, :body, :tag_list, review_images_images: [], category_ids: []) 
  end

  def validate_user
    @review = Review.find(params[:id])
    if @review.user != current_user
      flash[:alert] = "無効なURLです"
      redirect_back(fallback_location: school_review_path)
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_error_messages.html.erb
<% if @review.errors.present? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/reviews/_form.html.erb
<%= form_with model: [@school, @review], local: true do |f| %>
  
  <div class="form-group mt-3">
    <p class="label-font">
      タイトル
    </p>
    <%= f.text_field :title, class:"form-control" %>
  </div>

  <div class="form-group">
    <p class="label-font">
      本文
    </p>
    <%= f.text_area :body, size: "20x10", class:"form-control" %>
  </div>

  <div class="form-group">
    <p class="label-font">
      タグの入力
    </p>
    <%= f.text_field :tag_list, value: @review.tag_list.join(','), class:"form-control", placeholder: ",で区切るとタグを複数登録できます。" %>
  </div>

  <div class="category-form">
    <span class="category-form-title">
      <i class="fa fa-check-square-o" aria-hidden="true"></i>
      オススメポイント
    </span>
    <br>
    <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |category| %>
      <%= category.label do %>
        <%= category.check_box %>
        <%= category.text %>
      <% end %>
    <% end %>
  </div>

  <div class="form-group">
    <p class="label-font">
      写真を添付
    </p>
  <%= f.attachment_field :review_images_images, multiple: true, class:"btn-flat-simple"%>
  <br>
  </div>
  
  <div class="text-center my-3 ">
    <%= button_tag type: "submit", class: "btn-submit" do %>
      <i class="fa fa-check-square-o" aria-hidden="true"></i>
      投稿する
    <% end %>
  </div>
<% end %>

app/views/reviews/_photo_slide.html.erb
<div class="cp_cssslider2">
  <% review.review_images.each do |image| %>
    <div class="cp_slide_item2">
      <%= attachment_image_tag review.review_images.first, :image, :fill, 300, 200 %>
    </div>
  <% end %>
</div>

app/views/reviews/_tag_list.html.erb
<ul class="tag_card">
  <% tag_list.each do |tag| %>
    <li><%= link_to "＃#{tag}", root_path(tag_name: tag), class: "text-black" %></li>
  <% end %>
</li>

app/views/reviews/edit.html.erb
<% provide(:title, "レビューの編集：#{@review.title}")  %>
<div class="container">

  <div class="row">
    <%= link_to school_review_path, class:"btn-back" do %>
    <i class="fa fa-arrow-left" aria-hidden="true"></i> Back
    <% end %>
  </div>

  <%= render "schools/school_details", school: @school %>

  <div class="row">
    <div class="col-md-12 rev-card">
      <div class="rev-card-title">
        <i class="fa fa-check" aria-hidden="true"></i> レビューを編集する
      </div>
        <%= render "error_messages", review: @review %>
        <%= render "form", review: @review %>
    </div>
  </div>
</div>

app/views/reviews/index.html.erb
<% provide(:title, "レビューリスト")  %>
<div class="container">

  <%= link_to root_path, class:"btn-back" do %>
    <i class="fa fa-arrow-left" aria-hidden="true"></i> Back
  <% end %>

  <div class="row"> 
    <div class="col-md-12">
      <h1 class="title-rev">レビューリスト</h1>

        <div class="row">
          <div class="col-4">
            <div class="webkit-center hidden_box">
              <label for="label1">
                <h5 class="keyword-search">
                  <i class="fa fa-search" aria-hidden="true">
                    キーワードからレビューを検索する
                  </i>
                </h5>
              </label>
              <input type="checkbox" id="label1"/>
              <div class="hidden_show">
                  <%= render "layouts/search_form" %>
              </div>
            </div>
          </div>

          <div class="col-4">
            <h5 class="keyword-search">
              <i class="fa fa-hashtag" aria-hidden="true">
                <%= link_to "タグからレビューを検索する", alltags_path, style:"color: lightskyblue;" %>
              </i>
            </h5>
          </div>

          <div class="col-4">
            <h5 class="keyword-search">
              <i class="fa fa-building" aria-hidden="true">
                <%= link_to "学校からレビューを検索する", schools_path, style:"color: lightskyblue;" %>
              </i>
            </h5>
          </div>
        </div>

        <%= render "layouts/review_index", reviews: @reviews %>
      </div>
    </div>
  </div>
  <%= paginate @reviews %>
</div>

app/views/reviews/new.html.erb
<% provide(:title, "レビュー投稿")  %>

<div class="container">
  <%= link_to schools_path, class:"btn-back" do %>
  <i class="fa fa-arrow-left" aria-hidden="true"></i> Back
<% end %>

  <%= render "schools/school_details", school: @school %>
  <div class="footerpt"> 
  <div class="row">
    <div class="col-md-12 rev-card">
      <div class="rev-card-title">
        <i class="fa fa-check" aria-hidden="true"></i> レビューを投稿する
      </div>
      <%= render "error_messages", review: @review %>
      <%= render "form", review: @review%>
      </div>
    </div>
  </div>
</div>

app/views/reviews/search.html.erb
<% provide(:title, "「#{params[:search]}」の検索結果")  %>
<div class="container">
  <%= link_to reviews_index_path, class:"btn-back" do %>
  <i class="fa fa-arrow-left" aria-hidden="true"></i> Back
<% end %>
  <div class="row">
    <div class="col-md-12">
      <h1 class="title-h1">「<%= "#{params[:search]}" %>」の検索結果</h1>
      <%= render "layouts/review_index", reviews: @reviews %>
    </div>
  </div>
  <%= paginate @reviews %>
</div>

app/views/reviews/show.html.erb
<% provide(:title, @review.title)  %>
<div class="container">
  <%= link_to :back, class:"btn-back" do %>
  <i class="fa fa-arrow-left" aria-hidden="true"></i> Back
  <% end %>

  <div class="row">
    <div class="rev-card-school-details col-12">
       <!-- タイトル -->
      <div class="title-school">
        <%= @review.title %>
      </div>

      <!-- レビューに画像が添付されているか確認 -->
      <div class="col-md-6 float-right">
        <% if @review.review_images.present? %>
            <%= render "photo_slide", review: @review %>
        <% else %>
          <div class="cp_cssslider2">
            <div class="cp_slide_item2">
                <img class="card-img-top" src="/images/default.jpg" alt="no_image">
            </div>
          </div>
        <% end %>
      </div>

      <!-- レビュー本文 -->
      <div class="col-md-6 float-left">
        <div class="mt-4">
         <div class="review-form">
          <p><%= safe_join(@review.body.split("\n"), tag(:br)) %></p>
         </div>
        </div>
      </div>

      <!-- ユーザー -->
      <div class="col-md-6 float-left pt-4 pb-4">
        <div class="card-text-user">

        <%= link_to profile_path(id: @review.user.profile.id) do %>
        <h6 style="color:black;"><%= render 'layouts/profile_icon', profile: @review.user.profile %>
        <%= @review.user.profile.name %>さん</h6>
        <% end %>
        </div>

      </div>

      <!-- タグ -->
      <div class="col-md-6 float-left">
        <%= render "reviews/tag_list", tag_list: @review.tag_list %>
      </div>

       <!-- カテゴリー -->
       <div class="col-md-6 float-left">
        <div class="category-area">
          <span class="category-area-title"><i class="fa fa-check-square-o" aria-hidden="true"></i>オススメポイント</span>
          <% @review.categories.each do |category| %>
          <span class="badge badge-light">
            <%= link_to category_path(id: category.id), class: "text-black" do %>
              <i class="fa fa-thumb-tack" aria-hidden="true"></i> <%= category.name %>
            <% end %>
          </span>
          <% end %>
        </div>
      </div>

      <!-- いいね -->
      <div class="col float-left">
        <%= render "likes/like", review: @review %>
        <!-- 投稿日 -->
          <i class="fa fa-calendar" aria-hidden="true"></i> <%= @review.created_at.strftime("%Y年%m月%d日") %>
        <!-- レビューの編集・削除ボタン -->
        <% if @review.user == current_user %>
        <%=link_to edit_school_review_path, class:"btn-edit m-1" do %>
        <i class="fa fa-check-square-o" aria-hidden="true"></i> レビューを編集する
        <% end %>
        <%=link_to school_review_path, method: :delete, class:"btn-destory m-1",data: {confirm: "本当にこの投稿を削除しますか？" } do %>
        <i class="fa fa-trash-o" aria-hidden="true"></i> レビューを削除する
        <% end %>
        <% end %>
      </div>
    </div>
  </div>

      
  <!-- コメント -->
  <div class="row">
    <div class="col-md-6">
      <%= render partial: 'comments/index', locals: { comments: @comments } %>
    </div>
    <%= paginate @comments %>
    <% if user_signed_in? %>
    <div class="col-8">
      <div id="error_area">
        <%= render partial: 'comments/form', locals: { comment: @comment, review: @review } %>
      </div>
    </div>
    <% end %>
  </div>

  <div class="row">
    <div class="col">
     <%= render "schools/school_details", school: @school %>  
    </div>
  </div>
</div>