config/routes.rb
  Rails.application.routes.draw do
  get 'likes/create'
  get 'likes/destroy'
  get 'reviews/index'
  get "start", to: "static_pages#start"
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks",
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  get "alltags", to: "static_pages#alltags"
  get "search", to: "reviews#search"
  root 'static_pages#home'

  resources :schools do
    collection do   
      get :search
    end
    resources :reviews do
      resources :comments
    end
  end
  resources :likes, only: [:destroy, :create]  
  resources :notifications, only: :index
  resources :categories, only: [:index, :show, :new, :create, :destroy]
  resources :profiles, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :review_category_relations
  has_many :reviews, through: :review_category_relations
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review
  has_many :notifications, dependent: :destroy
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :review
  counter_culture :review
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :review, optional: true
  belongs_to :comment, optional: true
  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar
end

app/models/review.rb
class Review < ApplicationRecord
  acts_as_taggable
  belongs_to :user
  belongs_to :school
  has_many :review_images, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_rev_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  accepts_attachments_for :review_images, attachment: :image
  has_many :notifications, dependent: :destroy
  has_many :review_category_relations
  has_many :categories, through: :review_category_relations
  validates :title, presence: true, length: { maximum: 50 }
  validates :body, presence: true

  def like_rev(user)
    likes.create(user_id: user.id)
  end

  def un_like_rev(user)
    likes.find_by(user_id: user.id).destroy
  end

  def like_rev?(user)
    like_rev_users.include?(user)
  end

  def self.search(search)
    if search
      Review.where(['body LIKE ? OR title LIKE ?', "%#{search}%", "%#{search}%"])
    else
      Review.all
    end
  end

  def create_notification_like!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and review_id = ? and action = ? ", current_user.id, user_id, id, 'like'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        review_id: id,
        visited_id: user_id,
        action: 'like'
      )
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_user, comment_id)
    temp_ids = Comment.select(:user_id).where(review_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    notification = current_user.active_notifications.new(
      review_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/models/review_image.rb
class ReviewImage < ApplicationRecord
  belongs_to :review
  attachment :image
end

app/models/school.rb
class School < ApplicationRecord
  has_many :reviews, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  validates :address, presence: :true
  validates :res_id, uniqueness: true
  validates :name, presence: true
  scope :sorted, -> { order(created_at: :desc) }

  scope :search, -> (search_params) do
    return if search_params.blank?
    name_like(search_params[:name]).nation_is(search_params[:nation]).genre_is(search_params[:genre])
  end


  scope :name_like, -> (name) { where('name LIKE ?', "%#{name}%") if name.present? }
  scope :nation_is, -> (nation) { where('nation LIKE ?', "%#{nation}%") if nation.present? }
  scope :genre_is, -> (genre) { where('genre LiKE ? OR subgenre LIKE ?', "%#{genre}%", "%#{genre}%") if genre.present? }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :omniauthable, omniauth_providers: [:twitter]
  before_create :create_profile

  has_one :profile, dependent: :destroy
  has_many :review, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  def self.from_omniauth(auth)
    find_or_create_by(provider: auth["provider"], uid: auth["uid"]) do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.username = auth["info"]["nickname"]
      user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"]) do |user|
        user.attributes = params
      end
    else
      super
    end
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.username = "ゲストユーザー"
      user.confirmed_at = Time.now 
    end
  end

  private

  def create_profile
    build_profile
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
      title:       "School Review",
      description: "フィリピン／オーストラリアの語学学校レビューアプリ",
      keywords:    "フィリピン,オーストラリア,語学学校, 留学エージェント, Ruby, Rails",
      icon: image_url("/images/favicon.ico"), # favicon
      noindex: ! Rails.env.production?, # production環境以外はnoindex  
      charset: "UTF-8",
      # OGPの設定
      og: {
        title: "School Review",
        type: "website",
        url: request.original_url,
        image: image_url("/images/slide8.png"),
        site_name: "School Review",
        description: "フィリピン／オーストラリアの語学学校レビューアプリ",
        locale: "ja_JP"
      } 
    }
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  Copyright © since 2020 <a href="https://local-plan.com/">Local Plan</a> All Rights Reserved.
  <nav>
      <i class="fa fa-envelope-o" aria-hidden="true"></i>
      Contact: 
      <%= mail_to 'y.aoki.job@gmail.com', 'y.aoki.job@gmail.com', :encode => 'hex' %>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color:#2C7CFF;"> 
    <a class="navbar-brand" href="/"><img src="/images/Local-Plan-logo.png" alt="LocalPlanlogo" style="width:auto; height:60px;"></a>
      <button type="button" class="navbar-toggler hamburger" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-end" id="Navber">
        <ul class="navbar-nav mr-auto text-white">
          <li class="nav-item"><%= link_to "語学学校リスト", schools_path, class:"nav-link text-light" %></li>
          <li class="nav-item"><%= link_to "レビューリスト", reviews_index_path, class:"nav-link text-light" %></li>
        </ul>
        <ul class="navbar-nav">
          <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to new_school_path, class: "btn btn-info nav-rev-btn text-white" do %>
            <i class="fa fa-check" aria-hidden="true"></i>レビュー投稿
            <% end %>
          </li>   
          <li class="nav-item dropdown">
          <a href="" class="nav-link dropdown-toggle text-white" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= render 'layouts/profile_icon', profile: current_user.profile %>
              <%= current_user.profile.name %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "プロフィール", profile_path(id: current_user.profile.id), class: "dropdown-item" %>
              <%= render "notifications/circle" %>
              <%= link_to "アカウント情報の編集", edit_user_registration_path, class:"dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"dropdown-item", id: "log_out" %>
            </div>
          </li>
          <% else %>
            <li class="nav-item nav-link pointer text-white" id="signup-show" style="cursor:pointer">新規登録</li>
            <li class="nav-item nav-link pointer text-white" id="login-show" style="cursor:pointer">ログイン</li>
          <% end %>
        </ul>
      </div>  
    </nav>
</header>

app/views/layouts/_login.html.erb
<div class="login-modal-wrapper" id="login-modal">
  <div class="log-modal col-12">
    <div class="close-modal">
      <i class="fa fa-2x fa-times"></i>
    </div>
    <div id="login-form">
      <div class="title-sign">ログイン</div>
      <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
        <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"form-ctl", placeholder: "メールアドレス", id: "login_user_email" %>
        <%= f.password_field :password, autocomplete: "current-password", class:"form-ctl", placeholder: "パスワード", id: "login_user_password" %>
        <%= f.submit "ログインする", id:"submit-btn" %>
      <% end %>
      <%= link_to 'ゲストユーザーでログイン', users_guest_sign_in_path, method: :post, class: "guest-submit-btn" %>
      <br>
      <%= render "devise/shared/links" %>
    </div>
  </div>
</div>

app/views/layouts/_profile_icon.html.erb
<% if profile.avatar.attached? %>
  <%= image_tag(profile.avatar.variant(combine_options:{resize:"30x30^",crop:"30x30+0+0",gravity: :center}).processed, style: "border-radius: 4em;margin-bottom: 1px;") %>  
<% else %>
  <%= image_tag("default.jpg", size: '30x30' , style: "border-radius: 4em;margin-bottom: 1px;") %>
<% end %>

app/views/layouts/_profile_image.html.erb
<% if profile.avatar.attached? %>
  <%= image_tag profile.avatar %>
<% else %>
  <%= image_tag "no_image.png" %>
<% end %>

app/views/layouts/_review_index.html.erb
<div class="row">
<% if reviews.present? %>
  <% reviews.each do |review| %>
      <div class="card-deck">
        <div class ="col">
          <div class="card mt-4 shadow-sm" style="width: 15rem; height: 35rem;">
            <div class="card-body">
              <!-- イメージ -->
              <% if review.review_images.present? %>
                <%= attachment_image_tag review.review_images.first, :image, :fill, 200, 200 %>
              <% else %>
                <img class="card-img-top2" src="/images/default.jpg" alt="no_image" width="200px" height="200px" %>
              <% end %>     
              <!-- レビュータイトル -->
              <div class="card-title"><%= review.title %></div> 
              <!-- 本文 -->
              <div class="card-text">
                <%= truncate review.body, length: 13 do %>
                <% end %>
                    <%= link_to school_review_path(school_id: review.school_id, id: review.id), class: "btn-continue" do %>
                  <i class="fa fa-caret-right" aria-hidden="true"></i> 続きを見る
                <% end %>
                </div>

              <!-- 投稿者 -->
                <div class="card-text-user">
                  <%= link_to profile_path(id: review.user.profile.id) do %>
                    <h6 style="color:black;"><%= render 'layouts/profile_icon', profile: review.user.profile %>
                    <%= review.user.profile.name %>さん
                    </h6>
                  <% end %>
                </div>
              <!-- タグ -->
                <div class="card-tag">
                  <%= render "reviews/tag_list", tag_list: review.tag_list %>
                </div>
              <!-- 投稿日 -->
              <div class="card-time"><small class="text-muted">
                <i class="fa fa-calendar" aria-hidden="true"></i> 
                <%= review.created_at.strftime("%Y年%m月%d日") %>
              </small></div>
            </div>
          </div>
        </div>
      </div>
  <% end %>
<% else %>

  <div class="text-center p-5">
    <p>投稿はありません</p>
  </div>
  <% end %>
</div>

app/views/layouts/_search_form.html.erb
<%= form_with url: search_path, method: 'get', local: true, class: "form-inline my-2 my-lg-0" do |f| %>
  <%= f.text_field :search, class: "form-control mr-sm-2", placeholder: "キーワード" %>
  <%= f.submit '検索', name: nil, class: "btn btn-info my-2 my-sm-0" %>
<% end %>

app/views/layouts/_signup.html.erb
<div class="signup-modal-wrapper col-12" id="signup-modal">
  <div class="log-modal">
    <div class="close-modal">
      <i class="fa fa-2x fa-times"></i>
    </div>
    <div class="signup-form">
      <h2 class="title-sign">新規登録</h2>
      <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
        <%= render "devise/shared/error_messages", resource: resource %>
        <%= f.text_field :username, class: "form-ctl", placeholder: "名前(ニックネーム)", id: "new_profile_name" %>
        <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"form-ctl", placeholder: "メールアドレス", id: "new_user_email" %>
        <% if @minimum_password_length %>
          <em>(<%= @minimum_password_length %> 文字以上で入力)</em>
        <% end %><br />
        <%= f.password_field :password, autocomplete: "new-password", class:"form-ctl", placeholder: "パスワード", id: "new_user_password" %>
        <%= f.password_field :password_confirmation, autocomplete: "new-password", class:"form-ctl", placeholder: "パスワード(確認)", id: "new_user_password_confirmation" %>
        <%= f.submit "新規登録する" ,id:"submit-btn" %>
      <% end %>
      <%= link_to 'ゲストユーザーでログイン', users_guest_sign_in_path, method: :post, class: "guest-submit-btn" %>
      <br>
   

      <%- if devise_mapping.omniauthable? %>
        <%- resource_class.omniauth_providers.each do |provider| %>
          <%= link_to omniauth_authorize_path(resource_name, provider) do %>
            <div id="twitter-submit-btn">
              <i class="fa fa-twitter" aria-hidden="true"></i> Twitterで新規登録
            </div>
          <% end %><br />
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
  <%= favicon_link_tag '/images/favicon.ico'%>
    <%= display_meta_tags default_meta_tags %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width,initial-scale=1, minimum-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>
  
  <body>
    <%= render "layouts/header" %>
    <div class="notifications">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: key) %>
      <% end %>
    </div>
      <%= render "layouts/signup" %>
      <%= render "layouts/login" %>
      <%= yield %>
      <%= render "layouts/footer" %>
  </body>
</html>